name: GitHub Actions
run-name: Build project
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Use node version"
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: "Install dependencies"
        run: npm install
      - name: Build
        run: npm run build
