on:
  pull_request:
    types: [edited, synchronize, opened]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Use node version'
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Build'
        run: npm run build-ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Use node version'
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Linting with ESLint'
        run: npm run lint
